import { MarketPrice } from "../types/index";

export const MARKET_DATA: MarketPrice[] = [
  {
    culture:     "Maïs",
    emoji:       "🌽",
    prix_kg:     185,
    unite:       "FCFA/kg",
    marche:      "Marché Mokolo, Yaoundé",
    tendance:    "up",
    variation:   8,
    lastUpdated: "Chargement...",
  },
  {
    culture:     "Cacao",
    emoji:       "🍫",
    prix_kg:     1650,
    unite:       "FCFA/kg",
    marche:      "ONCC Bafoussam",
    tendance:    "up",
    variation:   45,
    lastUpdated: "Chargement...",
  },
  {
    culture:     "Manioc",
    emoji:       "🥔",
    prix_kg:     95,
    unite:       "FCFA/kg",
    marche:      "Marché Central, Douala",
    tendance:    "stable",
    variation:   0,
    lastUpdated: "Chargement...",
  },
  {
    culture:     "Arachides",
    emoji:       "🥜",
    prix_kg:     420,
    unite:       "FCFA/kg",
    marche:      "Marché Bali, Bamenda",
    tendance:    "down",
    variation:   -12,
    lastUpdated: "Chargement...",
  },
  {
    culture:     "Café Robusta",
    emoji:       "☕",
    prix_kg:     1200,
    unite:       "FCFA/kg",
    marche:      "ONCC Mbalmayo",
    tendance:    "up",
    variation:   30,
    lastUpdated: "Chargement...",
  },
  {
    culture:     "Banane Plantain",
    emoji:       "🍌",
    prix_kg:     145,
    unite:       "FCFA/kg",
    marche:      "Marché Essos, Yaoundé",
    tendance:    "down",
    variation:   -5,
    lastUpdated: "Chargement...",
  },
];
